import dinningTable from ".././assets/dinning-set.jpg";
import velvetSeat from ".././assets/velvet-seat.jpg";
import coffeeTable from ".././assets/coffee-table.jpg";
import sofa from ".././assets/ergonomic-chair.jpg";
import bookshelf from ".././assets/book-self.jpg";
import marbleTable from ".././assets/marble-table.jpg";
import upholsteredBed from ".././assets/upholstered-bed.jpg";
import outdoorFurniture from ".././assets/outdoor-furniture.jpg";
import officeErgonomic from ".././assets/office-ergonomic.jpg";
import tvStand from ".././assets/simple-tv-stand.jpg";
import wardrobe from ".././assets/walldrope.jpg";
import bedsideTable from ".././assets/bedside-table.jpg";
import sofaBed from ".././assets/sofa-bed.jpg";
import floatingWallShelf from "../../src/assets/floating-bookshelf.jpg";
import kidsStudyDesk from ".././assets/kids-study.jpg";
import woodenBench from ".././assets/wooden-bench.jpg";
import dressingTable from ".././assets/dressing-table.jpg";
import roundDinning from ".././assets/round-dinning-table.jpg";
import floorLamp from ".././assets/floor-lamp.jpg";
import lSofa from "../../src/assets/l-shaped-sofa.jpg";

const products = [
  {
    id: 1,
    name: "Oakwood Dining Table",
    description: "Solid oak rectangular dining table with a natural finish.",
    category: "Dining",
    sku: "OAK-DINE-001",
    price: 750,
    salesPrice: 699,
    currency: "USD",
    inStock: true,
    rating: 4.5,
    reviewsCount: 124,
    image: dinningTable,
  },
  {
    id: 2,
    name: "Velvet Accent Chair",
    description: "Elegant velvet upholstered accent chair with gold legs.",
    category: "Seating",
    sku: "VEL-CHAIR-002",
    price: 250,
    salesPrice: 199,
    currency: "USD",
    inStock: true,
    rating: 4.8,
    reviewsCount: 87,
    image: velvetSeat,
  },
  {
    id: 3,
    name: "Glass Coffee Table",
    description: "Modern coffee table with tempered glass top and steel frame.",
    category: "Living Room",
    sku: "GLS-COF-003",
    price: 320,
    salesPrice: 289,
    currency: "USD",
    inStock: true,
    rating: 4.3,
    reviewsCount: 53,
    image: coffeeTable,
  },
  {
    id: 4,
    name: "Leather Recliner Sofa",
    description: "Premium leather recliner sofa with cup holders.",
    category: "Living Room",
    sku: "LEA-SOFA-004",
    price: 1200,
    salesPrice: 1099,
    currency: "USD",
    inStock: true,
    rating: 4.7,
    reviewsCount: 210,
    image: sofa,
  },
  {
    id: 5,
    name: "Minimalist Bookshelf",
    description: "5-tier open shelf bookcase made of engineered wood.",
    category: "Storage",
    sku: "MIN-BOOK-005",
    price: 180,
    salesPrice: 159,
    currency: "USD",
    inStock: true,
    rating: 4.2,
    reviewsCount: 66,
    image: bookshelf,
  },
  {
    id: 6,
    name: "Marble Top Side Table",
    description: "Round side table with white marble top and golden frame.",
    category: "Living Room",
    sku: "MRB-SIDE-006",
    price: 220,
    salesPrice: 199,
    currency: "USD",
    inStock: true,
    rating: 4.6,
    reviewsCount: 74,
    image: marbleTable,
  },
  {
    id: 7,
    name: "Upholstered King Bed",
    description:
      "Luxury king-size bed with tufted headboard and storage drawers.",
    category: "Bedroom",
    sku: "UPH-BED-007",
    price: 950,
    salesPrice: 899,
    currency: "USD",
    inStock: true,
    rating: 4.9,
    reviewsCount: 143,
    image: upholsteredBed,
  },
  {
    id: 8,
    name: "Outdoor Patio Set",
    description: "Rattan 4-piece outdoor furniture set with cushions.",
    category: "Outdoor",
    sku: "OUT-PATIO-008",
    price: 680,
    salesPrice: 629,
    currency: "USD",
    inStock: true,
    rating: 4.4,
    reviewsCount: 58,
    image: outdoorFurniture,
  },
  {
    id: 9,
    name: "Office Ergonomic Chair",
    description: "Adjustable ergonomic office chair with lumbar support.",
    category: "Office",
    sku: "OFF-CHAIR-009",
    price: 300,
    salesPrice: 259,
    currency: "USD",
    inStock: true,
    rating: 4.7,
    reviewsCount: 312,
    image: officeErgonomic,
  },
  {
    id: 10,
    name: "Industrial TV Stand",
    description: "Wood and metal TV stand with cable management system.",
    category: "Living Room",
    sku: "IND-TV-010",
    price: 420,
    salesPrice: 389,
    currency: "USD",
    inStock: true,
    rating: 4.3,
    reviewsCount: 92,
    image: tvStand,
  },
  {
    id: 11,
    name: "Modern Wardrobe",
    description: "3-door wardrobe with sliding doors and mirror panel.",
    category: "Bedroom",
    sku: "MOD-WARD-011",
    price: 820,
    salesPrice: 769,
    currency: "USD",
    inStock: true,
    rating: 4.6,
    reviewsCount: 115,
    image: wardrobe,
  },
  {
    id: 12,
    name: "Rustic Bedside Table",
    description: "Compact bedside table with drawer and open shelf.",
    category: "Bedroom",
    sku: "RUS-BED-012",
    price: 150,
    salesPrice: 129,
    currency: "USD",
    inStock: true,
    rating: 4.2,
    reviewsCount: 37,
    image: bedsideTable,
  },
  {
    id: 13,
    name: "Convertible Sofa Bed",
    description: "Space-saving sofa that converts into a bed.",
    category: "Living Room",
    sku: "CON-SOF-013",
    price: 600,
    salesPrice: 549,
    currency: "USD",
    inStock: true,
    rating: 4.5,
    reviewsCount: 88,
    image: sofaBed,
  },
  {
    id: 14,
    name: "Floating Wall Shelf",
    description: "Set of 3 floating wall shelves for display and storage.",
    category: "Storage",
    sku: "FLT-SHLF-014",
    price: 90,
    salesPrice: 75,
    currency: "USD",
    inStock: true,
    rating: 4.1,
    reviewsCount: 42,
    image: floatingWallShelf,
  },
  {
    id: 15,
    name: "Kids Study Desk",
    description: "Adjustable height study desk with storage compartments.",
    category: "Kids",
    sku: "KID-DESK-015",
    price: 260,
    salesPrice: 229,
    currency: "USD",
    inStock: true,
    rating: 4.4,
    reviewsCount: 65,
    image: kidsStudyDesk,
  },
  {
    id: 16,
    name: "Reclaimed Wood Bench",
    description: "Rustic reclaimed wood bench with iron legs.",
    category: "Seating",
    sku: "REC-BENCH-016",
    price: 280,
    salesPrice: 249,
    currency: "USD",
    inStock: true,
    rating: 4.3,
    reviewsCount: 39,
    image: woodenBench,
  },
  {
    id: 17,
    name: "Luxury Dresser",
    description: "6-drawer dresser with soft-close mechanism.",
    category: "Bedroom",
    sku: "LUX-DRES-017",
    price: 700,
    salesPrice: 659,
    currency: "USD",
    inStock: true,
    rating: 4.6,
    reviewsCount: 101,
    image: dressingTable,
  },
  {
    id: 18,
    name: "Round Dining Set",
    description: "Round dining table with 4 cushioned chairs.",
    category: "Dining",
    sku: "RND-DINE-018",
    price: 880,
    salesPrice: 829,
    currency: "USD",
    inStock: true,
    rating: 4.7,
    reviewsCount: 76,
    image: roundDinning,
  },
  {
    id: 19,
    name: "Contemporary Floor Lamp",
    description: "Tall floor lamp with adjustable brightness.",
    category: "Lighting",
    sku: "CNT-LAMP-019",
    price: 180,
    salesPrice: 149,
    currency: "USD",
    inStock: true,
    rating: 4.5,
    reviewsCount: 54,
    image: floorLamp,
  },
  {
    id: 20,
    name: "L-Shaped Sectional Sofa",
    description: "Spacious L-shaped sectional with chaise lounge.",
    category: "Living Room",
    sku: "LSEC-SOFA-020",
    price: 1350,
    salesPrice: 1249,
    currency: "USD",
    inStock: true,
    rating: 4.8,
    reviewsCount: 198,
    image: lSofa,
  },
];
